version: "3.8"

services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - "30001:30001"
    volumes:
      - ./data/mongo-1:/data/db
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - "30002:30002"
    volumes:
      - ./data/mongo-2:/data/db
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:5
    container_name: mongo3
    ports:
      - "30003:30003"
    volumes:
      - ./data/mongo-3:/data/db
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    networks:
      - mongo-cluster

  mongo-init:
    image: mongo:5
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: "no"
    entrypoint: [ "bash", "-c", "
      sleep 10 &&
      mongosh --host mongo1 --port 30001 --eval '
        try {
          rs.initiate({
            _id: \"my-replica-set\",
            members: [
              { _id: 0, host: \"mongo1:30001\" },
              { _id: 1, host: \"mongo2:30002\" },
              { _id: 2, host: \"mongo3:30003\" }
            ]
          });
        } catch(e) { print(e); }
      '
    " ]
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
