version: "3.8"

services:
  mongo:
    image: mongo:5.0.5
    container_name: demo-mongo
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      retries: 30
      start_period: 10s
      timeout: 5s

  mongo-init:
    build:
      context: ./mongo-init
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
